# golangci-lint configuration for kubertino
# See https://golangci-lint.run/usage/configuration/
version: 2

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    # Required linters per architecture.md
    - gocyclo      # Cyclomatic complexity (max 15)
    - goconst      # Detect repeated strings
    - misspell     # Catch typos
    # Additional quality linters
    - errcheck     # Check error returns
    - govet        # Go vet examinations
    - ineffassign  # Detect ineffective assignments
    - staticcheck  # Static analysis
    - unused       # Detect unused code

# Note: gofmt formatting should be enforced separately via `go fmt` or CI checks
# Run: go fmt ./... before committing

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor